function preview(prn_tpl_code)
{
 var names = new Array();
  var values = new Array();
  names[0] = "TPL_CODE";
  values[0 ]= prn_tpl_code;
  names[1] = "PRINT_DATA";
  values[1] = createPrintData();

  var com = getCommunity();
  if (com != null)
    com.doRequestPage("fprint","MA_CASH",names,values,"");
}

function createPrintData()
{
	printData = "<delta><entity name=\"head\">";
	printData += "<field name=\"A\" value=\"安易公司工资表\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"L2\" value=\"!!!L2!!!\" />";
	printData += "<field name=\"L3\" value=\"!!!L3!!!\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.5\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.56\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"0\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"0\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA1\" />";
	printData += "<field name=\"B\" value=\"值VB1\" />";
	printData += "<field name=\"C\" value=\"值VC1\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA2\" />";
	printData += "<field name=\"B\" value=\"值VB2\" />";
	printData += "<field name=\"C\" value=\"值VC2\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA3\" />";
	printData += "<field name=\"B\" value=\"值VB3\" />";
	printData += "<field name=\"C\" value=\"值VC3\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA4\" />";
	printData += "<field name=\"B\" value=\"值VB4\" />";
	printData += "<field name=\"C\" value=\"值VC4\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "<entity name=\"body\">";
	printData += "<field name=\"A\" value=\"值VA5\" />";
	printData += "<field name=\"B\" value=\"值VB5\" />";
	printData += "<field name=\"C\" value=\"值VC5\" />";
	printData += "<field name=\"D\" value=\"1234.567\" />";
	printData += "</entity>";
	printData += "</delta>";
	
	return printData;
}